version: "3"

services:
  mangadex-auto-dl:
    image: ghcr.io/oliverilp/mangadex-auto-dl
    container_name: mangadex-auto-dl
    environment:
      - DL_INTERVAL=1
    volumes:
      - ./list.sh:/mangadex/list.sh
      - ./downloads:/downloads
